#!/usr/bin/python

import urwid
		
		
class BigTextDisplay:

	palette = [
        ('header',       'white',      'dark red',   'bold'),
    ('bigtext', 'white', 'black'),]

	def main(self):
		self.view, self.view2 = self.setup_view()
		self.loop = urwid.MainLoop(self.view, self.palette, 
			unhandled_input=self.unhandled_input)
		self.loop.run()

	def unhandled_input(self,key):
		if key in ('q', 'Q'):
		    raise urwid.ExitMainLoop()
		elif key in ('n', 'N'):
			self.loop.widget = self.view2
			self.loop.draw_screen()
		
	def setup_view(self):

		bt = urwid.BigText('I am ready to build', font=urwid.font.HalfBlock5x4Font())
		btwp = urwid.Padding(bt, "center", 'clip')

		btwp = urwid.Filler(btwp, 'middle', None, 7)

		hdr = urwid.Text("University of Southampton Linux Installer")
		hdr = urwid.AttrWrap(hdr, 'header')
		ftr = urwid.Text("bonemeal 0.1")
		ftr = urwid.AttrWrap(ftr, 'header')
		frame = urwid.Frame(header=hdr, body=btwp, footer=ftr)


		bt2 = urwid.BigText('oh...hai!', font=urwid.font.HalfBlock5x4Font())
		btwp2 = urwid.Padding(bt2, "center", 'clip')

		btwp2 = urwid.Filler(btwp2, 'middle', None, 7)

		hdr2 = urwid.Text("University of Southampton Linux Installer")
		hdr2 = urwid.AttrWrap(hdr2, 'header')
		ftr2 = urwid.Text("bonemeal 0.1")
		ftr2 = urwid.AttrWrap(ftr2, 'header')
		frame2 = urwid.Frame(header=hdr2, body=btwp2, footer=ftr2)

		return frame, frame2

def main():
    BigTextDisplay().main()
    
if '__main__'==__name__:
    main()


