#!/usr/bin/python

import urwid
import dmidecode

SETUP_TITLE           = 'Red Hat Enterprise Linux 7 Workstation Setup';
INSTALL_SERVER        = 'install.soton.ac.uk';
PUPPET_MASTER         = 'desktop.puppet.soton.ac.uk';
PUPPET_MASTER_CA_CERT = '/mnt/build/ssl/desktop.puppet.soton.ac.uk.pem';
PUPPET_SSL_ROOT       = '/var/lib/puppet/ssl';
SETUP_VERSION         = 'Version 20141119-1';
PUPPET_TYPE           = 'el7-workstation64';
	
class BigTextDisplay:

	palette = [
		('edit', 'black', 'light gray'),
        ('header',       'white',      'dark red',   'bold'),
    ('bigtext', 'white', 'black'),]

	def main(self):
		self.view, self.view2 = self.setup_view()
		self.loop = urwid.MainLoop(self.view, self.palette, 
			unhandled_input=self.unhandled_input)
		self.loop.run()

	def get_asset_tag(self):
		try:
			data = dmidecode.chassis().values()
			value = data[0]['data']['Serial Number'] 

			if value == "Not Specified":
				return ""
			if value == None:
				return ""
			if len(value) < 1:
				return ""

			return value

		except Exception as ex:
			return ""

	def unhandled_input(self,key):
		if key in ('q', 'Q'):
		    raise urwid.ExitMainLoop()
		elif key in ('n', 'N'):
			self.loop.widget = self.view2
			self.loop.draw_screen()
		
	def setup_view(self):

		div = urwid.Divider()

		bt = urwid.BigText('I am ready to build', font=urwid.font.HalfBlock5x4Font())
		btwp = urwid.Padding(bt, "center", 'clip')

		txt = urwid.Text(u"Press any key to get started",align='center')
		pile1 = urwid.Pile([btwp,div,txt])
		pile1 = urwid.Filler(pile1, 'middle', None, 7)

		hdr = urwid.Text("University of Southampton Linux Installer")
		hdr = urwid.AttrWrap(hdr, 'header')
		ftr = urwid.Text("bonemeal 0.1")
		ftr = urwid.AttrWrap(ftr, 'header')
		frame = urwid.Frame(header=hdr, body=pile1, footer=ftr)

		htxt = urwid.Text(u" Welcome to the RHEL post-installation setup.",align='left')
		tag = self.get_asset_tag()
		print tag
		ed = urwid.Edit(caption=('header',"    UOS Number:  "),edit_text=tag)
		ed = urwid.AttrMap(ed, 'edit')
		ed2 = urwid.Edit(caption=('header',"      Location:  "))
		ed2 = urwid.AttrMap(ed2, 'edit')
		ed3 = urwid.Edit(caption=('header',"    User/Owner:  "))
		ed3 = urwid.AttrMap(ed3, 'edit')

		pile = urwid.Pile([div,htxt,div,ed,div,ed2,div,ed3])
		fill = urwid.Filler(pile, 'top')

		frame2 = urwid.Frame(header=hdr, body=fill, footer=ftr)

		return frame, frame2

def main():
    BigTextDisplay().main()
    
if '__main__'==__name__:
    main()


