#!/usr/bin/python

import urwid
		
		
class BigTextDisplay:

	palette = [
		('edit', 'black', 'light gray'),
        ('header',       'white',      'dark red',   'bold'),
    ('bigtext', 'white', 'black'),]

	def main(self):
		self.view, self.view2 = self.setup_view()
		self.loop = urwid.MainLoop(self.view, self.palette, 
			unhandled_input=self.unhandled_input)
		self.loop.run()

	def unhandled_input(self,key):
		if key in ('q', 'Q'):
		    raise urwid.ExitMainLoop()
		elif key in ('n', 'N'):
			self.loop.widget = self.view2
			self.loop.draw_screen()
		
	def setup_view(self):

		bt = urwid.BigText('I am ready to build', font=urwid.font.HalfBlock5x4Font())
		btwp = urwid.Padding(bt, "center", 'clip')

		btwp = urwid.Filler(btwp, 'middle', None, 7)

		hdr = urwid.Text("University of Southampton Linux Installer")
		hdr = urwid.AttrWrap(hdr, 'header')
		ftr = urwid.Text("bonemeal 0.1")
		ftr = urwid.AttrWrap(ftr, 'header')
		frame = urwid.Frame(header=hdr, body=btwp, footer=ftr)



		div = urwid.Divider()
		txt = urwid.Text(u"    Hello World",align='left')
		ed = urwid.Edit(caption="    Text Here:  ")
		ed = urwid.AttrMap(ed, 'edit')

		pile = urwid.Pile([ed,div,ed,div,ed])
		fill = urwid.Filler(pile, 'middle')

		hdr2 = urwid.Text("University of Southampton Linux Installer")
		hdr2 = urwid.AttrWrap(hdr2, 'header')
		ftr2 = urwid.Text("bonemeal 0.1")
		ftr2 = urwid.AttrWrap(ftr2, 'header')
		frame2 = urwid.Frame(header=hdr2, body=fill, footer=ftr2)

		return frame, frame2

def main():
    BigTextDisplay().main()
    
if '__main__'==__name__:
    main()


